name: ubuntu-linux conda-build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        python --version
        conda install python=3.9
        conda install -c astra-toolbox astra-toolbox
        conda install -c conda-forge matplotlib pip xfab
    - name: test flyxdm
      run: |
        python -c "import flyxdm"
