name: macos conda-build

on: [push]


jobs:
  build-mac:
    runs-on: macos-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up conda with Python 3.8
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: '3.8'
        auto-update-conda: true
    - name: Install dependencies
      shell: bash -el {0}
      run: |
        python --version
        conda install -c astra-toolbox astra-toolbox
        conda install -c conda-forge matplotlib xfab
        python -m pip install .
    - name: test flyxdm
      shell: bash -el {0}
      run: |
        python -c "import flyxdm"
